# Generated by Django 4.2.1 on 2026-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_uid', models.UUIDField(unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('registration_number', models.CharField(max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('ROADSTER', 'ROADSTER')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
