# Generated by Django 4.2.1 on 2026-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_uid', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('CANCELED', 'CANCELED')], max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
