# Generated by Django 4.2.1 on 2026-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_uid', models.UUIDField(unique=True)),
                ('username', models.CharField(max_length=80)),
                ('payment_uid', models.UUIDField()),
                ('car_uid', models.UUIDField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], max_length=20)),
            ],
            options={
                'db_table': 'rental',
            },
        ),
    ]
